export const enum Paths {
  Example = 'example',
  Startup = 'startup',
  Home = 'home',
  SignUp = 'signup',
  Login = 'login',
  Dashboard = 'dashboard',
  DashboardHome = 'dashboardhome',
  Layout = 'layout',
  SelectRide = 'selectride',
  ConfirmRide = 'confirmride',
  SelectDestination = 'selectdestination',
  SelectSeat = 'selectSeat',
  SelectPickupLocation = 'selectpickuplocation',
  SelectPreference = 'selectPreference',
  RiderDetails = 'riderDetails',
  RideDetails = 'rideDetails',
  DriverDetails = 'driverDetails',
  Services = 'Services',
  Profile = 'Profile',
}
